### ISSUE TITLE
Editor UI: 2d viewport

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-new-features-3.1#10]
Merge this with Editor UI basic tour?
Did the toolbar's tools change? Scale, change obj pivot
Mention Alt RMB to pick through even if not new (+ corresponding tool)
Compare the old and new layout
Zoom in and out with KBD

**Comment by henriiquecampos** [comment]
Closing this, video is up on dropbox, I can reopen the issue if there is something missing

**Comment by NathanLovato** [comment]
Just watched it, all good, thanks :)
