### ISSUE TITLE
Editor UI: 3d viewport

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-new-features-3.1#11]
Improved grid and interactions
New 3d gizmo
Gizmos visibility

**Comment by guilhermehto** [comment]
@NathanLovato what do you think of covering the 3D editor in general, together with the new features? The video won't be too long I believe.

**Comment by NathanLovato** [comment]
Yup, I'll leave it up to you.

**Comment by guilhermehto** [comment]
Done, it's going to be rendered tonight and uploaded tomorrow.
