### ISSUE TITLE
OpenSimplexNoise: Dissolve shader

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-new-features-3.1#15]
Use the dissolve shader from the 3.1 release trailer to show how to use a procedural noise texture and create an impressive effect. We can rewrite it in visual shader for the visual shader tutorial.

**Comment by henriiquecampos** [comment]
Is the dissolve shader from the release trailer available somewhere?

**Comment by NathanLovato** [comment]
Yup, I've just done the visual shader video, uploading it to the new-features-godot-3.1 repo now

**Comment by NathanLovato** [comment]
Actually, we've got a tutorial about procedural noise, and I've made the tutorial about the dissolve shader for the visual shader editor hands-on overview, so I think it's not worth doing this one right now.
