### ISSUE TITLE
GDScript: optional static typing

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-new-features-3.1#17]
We wrote the optional static typing page in gdscript in the official manual. This is going to be the corresponding video tutorial.

Explain the difference between static and dynamic types, the advantages and drawbacks of each (reuse slide/explanation from the GDScript intro tutorial: https://youtu.be/UcdwP1Q2UlU?t=733). Here we can link to the gdscript intro video
Use the docs article: https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/static_typing.html

**Comment by henriiquecampos** [comment]
What's the scope of the issue? Is making a new presentation **like** in the GDScript intro tutorial in the scope, or the **reuse** is more about referencing the intro video to setup the ground?

**Comment by NathanLovato** [comment]
The idea is to make a pretty complete, hands-on lesson about static typing. How to get type hint completion, showing error reporting etc. 

@guilhermehto didn't you make a video tutorial about that already? I'm not sure anymore. If you did already, we should just double check if there's anything new, or ways to add to the video.

**Comment by guilhermehto** [comment]
No, I only wrote the first version of the article :)
