### ISSUE TITLE
Code editor: improved search

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-new-features-3.1#19]
Find and replace in all files
Improved search in docs

Show the difference between 3.0 and 3.1

**Comment by henriiquecampos** [comment]
Can I try this one? I used it quite a bit during the refactoring of Moon Cheeser :grin:

**Comment by NathanLovato** [comment]
Sure! You can use moon cheeser for the video too

**Comment by henriiquecampos** [comment]
@NathanLovato what do you think about breaking this into 2 videos?

**Godot 3.1 Improved Help System** and **Godot 3.1 New Find & Replace Project Wide**

I just finished the review on the Improved Help System, i.e. docs, and it is quite self contained, there is room for a hook for the find and replace tho.

**Comment by NathanLovato** [comment]
If you want, but is there enough content to do more than 2-3mn videos? If not, better have one 5-6mn video. This series should focus on improvements and new features, not cover the basics. IIRC when it comes to the docs, the main improvement is the search bar is now consistent with the script editor.

**Comment by henriiquecampos** [comment]
Final cut of the Help System is around 7min long, these are the topics I covered:

- Quick show the 3.0 help system, for comparison purpose
- The Class Search Menu and the Custom Search menu were merged into a single Search Menu
- The Search Bar
    - Occurrences are niched in foldable classes
    - Search filters (class, method, property, etc...
    - Case Sensitive Search
- Opening the docs through the SceneTree dock 

I will record the Find&Replace to see if it can fit into a less than 12min video. The topics covered will be:
- Find occurrences project-wide and its features, like defining a folder scope, match case, whole word, etc...
- The Search Results tab and its features, like clicking on an occurrence to open it in the Script Editor
- Replace and how to filter what will actually be replaced (checking off the marks so you can cherrypick occurrences, etc...)

**Comment by NathanLovato** [comment]
It's good for 2 videos then! Can you create and self assign a second issue?

**Comment by henriiquecampos** [comment]
Video is done! So, closing it for now, we can reopen if there's something to fix.
