### ISSUE TITLE
2d meshes

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-new-features-3.1#21]
Show how to create 2d meshes to optimize the rendering of sprites.

This is **not** about animation. This is about the `Sprite -> convert to 2d mesh` feature.

![image](https://user-images.githubusercontent.com/12694995/54666316-bcfc5680-4ae9-11e9-8f31-13c0ef3dd39e.png)

**Comment by henriiquecampos** [comment]
Can I pick this one as well? I am really interested in exploring this feature, since its announcement :sweat_smile: 

Is this the Godette sprite on [Open RPG?](https://github.com/GDquest/godot-open-rpg)

**Comment by NathanLovato** [comment]
Sure! And yes, this is Godette from openRPG

**Comment by henriiquecampos** [comment]
Video is done! So, closing it for now, we can reopen if there's something to fix.
