### ISSUE TITLE
Visual Scripting: Getting Started

### ISSUE THREAD

**Issue by guilhermehto** [GDquest/godot-new-features-3.1#41]
Create a 2D game using only visual scripting

**Comment by NathanLovato** [comment]
Could you also:

- Mention upfront who visual scripting is for: designers, non-devs
- You can create custom nodes from gdscript, to create project-specific, designer-friendly nodes
- Mention the limitations of this language at the moment

See https://docs.godotengine.org/en/latest/getting_started/scripting/visual_script/getting_started.html

You can keep the game simple, even reuse a project from another tutorial, as VS becomes heavy quickly. Even just basic character movement in a platformer would be fine (move and jump)
